import Foundation

#if canImport(AppKit)
import AppKit
import CoreGraphics
import CoreText
#endif

/// Concrete implementation of ExportService that writes transcripts (and optional summaries)
/// to local files in various formats.
public final class FileExportService: ExportService, Sendable {
    public init() {}

    public func export(
        transcript: Transcript,
        summary: Summary?,
        format: ExportFormat,
        to destinationURL: URL
    ) async throws -> URL {
        // Ensure parent directory exists
        let parentDir = destinationURL.deletingLastPathComponent()
        try FileManager.default.createDirectory(at: parentDir, withIntermediateDirectories: true)

        let content: String
        switch format {
        case .markdown:
            content = renderMarkdown(transcript: transcript, summary: summary)
        case .plainText:
            content = renderPlainText(transcript: transcript, summary: summary)
        case .json:
            content = try renderJSON(transcript: transcript, summary: summary)
        case .rtf:
            content = renderRTF(transcript: transcript, summary: summary)
        case .subtitles:
            content = renderSRT(transcript: transcript)
        case .pdf:
            try await renderPDF(transcript: transcript, summary: summary, to: destinationURL)
            return destinationURL
        }

        try content.write(to: destinationURL, atomically: true, encoding: .utf8)
        return destinationURL
    }

    // MARK: - Format Renderers

    private func renderMarkdown(transcript: Transcript, summary: Summary?) -> String {
        var md = ""
        md += "# Transcript: \(transcript.id.uuidString)\n\n"
        md += "- **Recording ID:** \(transcript.recordingID.uuidString)\n"
        md += "- **Language:** \(transcript.languageCode)\n"
        md += "- **Model:** \(transcript.modelUsed)\n"
        md += "- **Generated:** \(ISO8601DateFormatter().string(from: transcript.generatedAt))\n"
        md += "- **Speakers:** \(transcript.speakers.map { $0.label }.joined(separator: ", "))\n\n"
        md += "## Transcript\n\n"

        for segment in transcript.segments {
            let speakerLabel = speakerLabel(for: segment, in: transcript)
            let timeRange = formatTimeRange(start: segment.startTime, end: segment.endTime)
            md += "**[\(timeRange)] \(speakerLabel):** \(segment.text)\n\n"
        }

        if let summary = summary {
            md += "---\n\n"
            md += "## Summary\n\n"
            md += "### Overview\n\(summary.overview)\n\n"
            if !summary.keyPoints.isEmpty {
                md += "### Key Points\n"
                for point in summary.keyPoints {
                    md += "- \(point)\n"
                }
                md += "\n"
            }
            if !summary.decisions.isEmpty {
                md += "### Decisions\n"
                for decision in summary.decisions {
                    md += "- \(decision)\n"
                }
                md += "\n"
            }
            if !summary.actionItems.isEmpty {
                md += "### Action Items\n"
                for item in summary.actionItems {
                    md += "- \(item.text)"
                    if let ownerID = item.ownerSpeakerID,
                       let owner = transcript.speakers.first(where: { $0.id == ownerID }) {
                        md += " (@\(owner.label))"
                    }
                    md += "\n"
                }
                md += "\n"
            }
            md += "---\n"
            md += "*Summary generated by \(summary.generatedByModel) at \(ISO8601DateFormatter().string(from: summary.generatedAt))*\n"
        }

        return md
    }

    private func renderPlainText(transcript: Transcript, summary: Summary?) -> String {
        var txt = ""
        txt += "Transcript: \(transcript.id.uuidString)\n"
        txt += "Recording ID: \(transcript.recordingID.uuidString)\n"
        txt += "Language: \(transcript.languageCode)\n"
        txt += "Model: \(transcript.modelUsed)\n"
        txt += "Generated: \(ISO8601DateFormatter().string(from: transcript.generatedAt))\n"
        txt += "Speakers: \(transcript.speakers.map { $0.label }.joined(separator: ", "))\n\n"
        txt += "=== TRANSCRIPT ===\n\n"

        for segment in transcript.segments {
            let speakerLabel = speakerLabel(for: segment, in: transcript)
            let timeRange = formatTimeRange(start: segment.startTime, end: segment.endTime)
            txt += "[\(timeRange)] \(speakerLabel): \(segment.text)\n"
        }

        if let summary = summary {
            txt += "\n=== SUMMARY ===\n\n"
            txt += "Overview: \(summary.overview)\n\n"
            if !summary.keyPoints.isEmpty {
                txt += "Key Points:\n"
                for point in summary.keyPoints {
                    txt += "  - \(point)\n"
                }
                txt += "\n"
            }
            if !summary.decisions.isEmpty {
                txt += "Decisions:\n"
                for decision in summary.decisions {
                    txt += "  - \(decision)\n"
                }
                txt += "\n"
            }
            if !summary.actionItems.isEmpty {
                txt += "Action Items:\n"
                for item in summary.actionItems {
                    txt += "  - \(item.text)"
                    if let ownerID = item.ownerSpeakerID,
                       let owner = transcript.speakers.first(where: { $0.id == ownerID }) {
                        txt += " (@\(owner.label))"
                    }
                    txt += "\n"
                }
                txt += "\n"
            }
            txt += "Summary generated by \(summary.generatedByModel) at \(ISO8601DateFormatter().string(from: summary.generatedAt))\n"
        }

        return txt
    }

    private func renderJSON(transcript: Transcript, summary: Summary?) throws -> String {
        struct ExportPayload: Codable {
            let transcript: Transcript
            let summary: Summary?
        }
        let payload = ExportPayload(transcript: transcript, summary: summary)
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        let data = try encoder.encode(payload)
        return String(data: data, encoding: .utf8)!
    }

    private func renderRTF(transcript: Transcript, summary: Summary?) -> String {
        let plainText = renderPlainText(transcript: transcript, summary: summary)
        // Minimal valid RTF wrapper
        // Escape backslashes and braces for RTF
        let escaped = plainText
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "{", with: "\\{")
            .replacingOccurrences(of: "}", with: "\\}")
            .replacingOccurrences(of: "\n", with: "\\par ")
        return "{\\rtf1\\ansi\\deff0 \(escaped)}"
    }

    private func renderSRT(transcript: Transcript) -> String {
        var srt = ""
        for (index, segment) in transcript.segments.enumerated() {
            let start = formatSRTTime(segment.startTime)
            let end = formatSRTTime(segment.endTime)
            let speakerLabel = speakerLabel(for: segment, in: transcript)
            srt += "\(index + 1)\n"
            srt += "\(start) --> \(end)\n"
            srt += "\(speakerLabel): \(segment.text)\n\n"
        }
        return srt
    }

    private func renderPDF(
        transcript: Transcript,
        summary: Summary?,
        to destinationURL: URL
    ) async throws {
        #if canImport(AppKit)
        let plainText = renderPlainText(transcript: transcript, summary: summary)

        var mediaBox = CGRect(x: 0, y: 0, width: 612, height: 792) // US Letter
        guard let context = CGContext(destinationURL as CFURL, mediaBox: &mediaBox, nil) else {
            throw ExportError.writeFailed(reason: "Could not create PDF graphics context for \(destinationURL.path)")
        }

        let margin: CGFloat = 72
        let textRect = mediaBox.insetBy(dx: margin, dy: margin)

        let attributedString = NSAttributedString(
            string: plainText,
            attributes: [
                .font: NSFont.monospacedSystemFont(ofSize: 11, weight: .regular),
                .foregroundColor: NSColor.black
            ]
        )
        let framesetter = CTFramesetterCreateWithAttributedString(attributedString)
        let fullLength = attributedString.length
        let path = CGPath(rect: textRect, transform: nil)

        var textPosition = 0
        repeat {
            context.beginPDFPage(nil)

            let frame = CTFramesetterCreateFrame(
                framesetter,
                CFRangeMake(textPosition, 0),
                path,
                nil
            )
            CTFrameDraw(frame, context)

            let visibleRange = CTFrameGetVisibleStringRange(frame)
            // Guard against an infinite loop if a frame somehow fits zero
            // characters (e.g. a pathologically tiny page) — bail rather
            // than hang generating pages forever.
            guard visibleRange.length > 0 else {
                context.endPDFPage()
                break
            }
            textPosition += visibleRange.length

            context.endPDFPage()
        } while textPosition < fullLength

        context.closePDF()
        #else
        // Fallback: write plain text with .pdf extension (best effort on non-macOS)
        let plainText = renderPlainText(transcript: transcript, summary: summary)
        try plainText.write(to: destinationURL, atomically: true, encoding: .utf8)
        #endif
    }

    // MARK: - Helpers

    private func speakerLabel(for segment: TranscriptSegment, in transcript: Transcript) -> String {
        guard let speakerID = segment.speakerID,
              let speaker = transcript.speakers.first(where: { $0.id == speakerID }) else {
            return "Unknown"
        }
        return speaker.label
    }

    private func formatTimeRange(start: TimeInterval, end: TimeInterval) -> String {
        let startStr = formatTime(start)
        let endStr = formatTime(end)
        return "\(startStr) – \(endStr)"
    }

    private func formatTime(_ time: TimeInterval) -> String {
        let hours = Int(time) / 3600
        let minutes = (Int(time) % 3600) / 60
        let seconds = Int(time) % 60
        let millis = Int((time.truncatingRemainder(dividingBy: 1)) * 1000)
        return String(format: "%02d:%02d:%02d.%03d", hours, minutes, seconds, millis)
    }

    private func formatSRTTime(_ time: TimeInterval) -> String {
        let hours = Int(time) / 3600
        let minutes = (Int(time) % 3600) / 60
        let seconds = Int(time) % 60
        let millis = Int((time.truncatingRemainder(dividingBy: 1)) * 1000)
        return String(format: "%02d:%02d:%02d,%03d", hours, minutes, seconds, millis)
    }
}